# Configuration for SSD with ResNet50 backbone

backbone:
  type: resnet50
  args:
    pretrained: true
    trainable_layers: 3  # Number of layers to fine-tune

detector:
  type: ssd
  args:
    min_scale: 0.2
    max_scale: 0.9
    aspect_ratios:
      - [1.0, 2.0, 0.5]  # For layer1
      - [1.0, 2.0, 0.5, 3.0, 0.33]  # For layer2
      - [1.0, 2.0, 0.5, 3.0, 0.33]  # For layer3
      - [1.0, 2.0, 0.5, 3.0, 0.33]  # For layer4
      - [1.0, 2.0, 0.5]  # For extra layer 1
      - [1.0, 2.0, 0.5]  # For extra layer 2

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0005
  momentum: 0.9
  lr_scheduler:
    type: reduce_on_plateau
    patience: 5
    factor: 0.1
    min_lr: 0.00001
  
  # Data augmentation
  augmentation:
    horizontal_flip: true
    random_crop: true
    color_jitter: true
    normalize: true

# Evaluation settings
evaluation:
  batch_size: 16
  iou_threshold: 0.5
  score_threshold: 0.5
  max_detections: 100